/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedServiceRouteImport } from './routes/_authenticated/service'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPurchaseRouteImport } from './routes/_authenticated/purchase'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedManufacturingRouteImport } from './routes/_authenticated/manufacturing'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedBranchesRouteImport } from './routes/_authenticated/branches'
import { Route as AuthenticatedAmcRouteImport } from './routes/_authenticated/amc'
import { Route as AuthenticatedAccountingRouteImport } from './routes/_authenticated/accounting'
import { Route as AuthenticatedAccountingIndexRouteImport } from './routes/_authenticated/accounting.index'
import { Route as AuthenticatedUsersRolesRouteImport } from './routes/_authenticated/users.roles'
import { Route as AuthenticatedAccountingPeriodsRouteImport } from './routes/_authenticated/accounting.periods'
import { Route as AuthenticatedAccountingJournalsRouteImport } from './routes/_authenticated/accounting.journals'
import { Route as AuthenticatedAccountingChartRouteImport } from './routes/_authenticated/accounting.chart'
import { Route as AuthenticatedAccountingBranchPnlRouteImport } from './routes/_authenticated/accounting.branch-pnl'
import { Route as AuthenticatedAccountingAnalyticRouteImport } from './routes/_authenticated/accounting.analytic'
import { Route as AuthenticatedAccountingAccountsRouteImport } from './routes/_authenticated/accounting.accounts'
import { Route as AuthenticatedAccountingEntriesNewRouteImport } from './routes/_authenticated/accounting.entries.new'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServiceRoute = AuthenticatedServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchaseRoute = AuthenticatedPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManufacturingRoute =
  AuthenticatedManufacturingRouteImport.update({
    id: '/manufacturing',
    path: '/manufacturing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAmcRoute = AuthenticatedAmcRouteImport.update({
  id: '/amc',
  path: '/amc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountingRoute = AuthenticatedAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountingIndexRoute =
  AuthenticatedAccountingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedUsersRolesRoute = AuthenticatedUsersRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)
const AuthenticatedAccountingPeriodsRoute =
  AuthenticatedAccountingPeriodsRouteImport.update({
    id: '/periods',
    path: '/periods',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingJournalsRoute =
  AuthenticatedAccountingJournalsRouteImport.update({
    id: '/journals',
    path: '/journals',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingChartRoute =
  AuthenticatedAccountingChartRouteImport.update({
    id: '/chart',
    path: '/chart',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingBranchPnlRoute =
  AuthenticatedAccountingBranchPnlRouteImport.update({
    id: '/branch-pnl',
    path: '/branch-pnl',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingAnalyticRoute =
  AuthenticatedAccountingAnalyticRouteImport.update({
    id: '/analytic',
    path: '/analytic',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingAccountsRoute =
  AuthenticatedAccountingAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingEntriesNewRoute =
  AuthenticatedAccountingEntriesNewRouteImport.update({
    id: '/entries/new',
    path: '/entries/new',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/accounting': typeof AuthenticatedAccountingRouteWithChildren
  '/amc': typeof AuthenticatedAmcRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/hr': typeof AuthenticatedHrRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/manufacturing': typeof AuthenticatedManufacturingRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/purchase': typeof AuthenticatedPurchaseRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/service': typeof AuthenticatedServiceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/accounting/accounts': typeof AuthenticatedAccountingAccountsRoute
  '/accounting/analytic': typeof AuthenticatedAccountingAnalyticRoute
  '/accounting/branch-pnl': typeof AuthenticatedAccountingBranchPnlRoute
  '/accounting/chart': typeof AuthenticatedAccountingChartRoute
  '/accounting/journals': typeof AuthenticatedAccountingJournalsRoute
  '/accounting/periods': typeof AuthenticatedAccountingPeriodsRoute
  '/users/roles': typeof AuthenticatedUsersRolesRoute
  '/accounting/': typeof AuthenticatedAccountingIndexRoute
  '/accounting/entries/new': typeof AuthenticatedAccountingEntriesNewRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/amc': typeof AuthenticatedAmcRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/hr': typeof AuthenticatedHrRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/manufacturing': typeof AuthenticatedManufacturingRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/purchase': typeof AuthenticatedPurchaseRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/service': typeof AuthenticatedServiceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/accounting/accounts': typeof AuthenticatedAccountingAccountsRoute
  '/accounting/analytic': typeof AuthenticatedAccountingAnalyticRoute
  '/accounting/branch-pnl': typeof AuthenticatedAccountingBranchPnlRoute
  '/accounting/chart': typeof AuthenticatedAccountingChartRoute
  '/accounting/journals': typeof AuthenticatedAccountingJournalsRoute
  '/accounting/periods': typeof AuthenticatedAccountingPeriodsRoute
  '/users/roles': typeof AuthenticatedUsersRolesRoute
  '/accounting': typeof AuthenticatedAccountingIndexRoute
  '/accounting/entries/new': typeof AuthenticatedAccountingEntriesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/accounting': typeof AuthenticatedAccountingRouteWithChildren
  '/_authenticated/amc': typeof AuthenticatedAmcRoute
  '/_authenticated/branches': typeof AuthenticatedBranchesRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/hr': typeof AuthenticatedHrRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/manufacturing': typeof AuthenticatedManufacturingRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/purchase': typeof AuthenticatedPurchaseRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/service': typeof AuthenticatedServiceRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/accounting/accounts': typeof AuthenticatedAccountingAccountsRoute
  '/_authenticated/accounting/analytic': typeof AuthenticatedAccountingAnalyticRoute
  '/_authenticated/accounting/branch-pnl': typeof AuthenticatedAccountingBranchPnlRoute
  '/_authenticated/accounting/chart': typeof AuthenticatedAccountingChartRoute
  '/_authenticated/accounting/journals': typeof AuthenticatedAccountingJournalsRoute
  '/_authenticated/accounting/periods': typeof AuthenticatedAccountingPeriodsRoute
  '/_authenticated/users/roles': typeof AuthenticatedUsersRolesRoute
  '/_authenticated/accounting/': typeof AuthenticatedAccountingIndexRoute
  '/_authenticated/accounting/entries/new': typeof AuthenticatedAccountingEntriesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/accounting'
    | '/amc'
    | '/branches'
    | '/crm'
    | '/hr'
    | '/inventory'
    | '/manufacturing'
    | '/payroll'
    | '/profile'
    | '/projects'
    | '/purchase'
    | '/reports'
    | '/sales'
    | '/service'
    | '/settings'
    | '/users'
    | '/accounting/accounts'
    | '/accounting/analytic'
    | '/accounting/branch-pnl'
    | '/accounting/chart'
    | '/accounting/journals'
    | '/accounting/periods'
    | '/users/roles'
    | '/accounting/'
    | '/accounting/entries/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/amc'
    | '/branches'
    | '/crm'
    | '/hr'
    | '/inventory'
    | '/manufacturing'
    | '/payroll'
    | '/profile'
    | '/projects'
    | '/purchase'
    | '/reports'
    | '/sales'
    | '/service'
    | '/settings'
    | '/users'
    | '/'
    | '/accounting/accounts'
    | '/accounting/analytic'
    | '/accounting/branch-pnl'
    | '/accounting/chart'
    | '/accounting/journals'
    | '/accounting/periods'
    | '/users/roles'
    | '/accounting'
    | '/accounting/entries/new'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/accounting'
    | '/_authenticated/amc'
    | '/_authenticated/branches'
    | '/_authenticated/crm'
    | '/_authenticated/hr'
    | '/_authenticated/inventory'
    | '/_authenticated/manufacturing'
    | '/_authenticated/payroll'
    | '/_authenticated/profile'
    | '/_authenticated/projects'
    | '/_authenticated/purchase'
    | '/_authenticated/reports'
    | '/_authenticated/sales'
    | '/_authenticated/service'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/accounting/accounts'
    | '/_authenticated/accounting/analytic'
    | '/_authenticated/accounting/branch-pnl'
    | '/_authenticated/accounting/chart'
    | '/_authenticated/accounting/journals'
    | '/_authenticated/accounting/periods'
    | '/_authenticated/users/roles'
    | '/_authenticated/accounting/'
    | '/_authenticated/accounting/entries/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/service': {
      id: '/_authenticated/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof AuthenticatedServiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase': {
      id: '/_authenticated/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof AuthenticatedPurchaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manufacturing': {
      id: '/_authenticated/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof AuthenticatedManufacturingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/amc': {
      id: '/_authenticated/amc'
      path: '/amc'
      fullPath: '/amc'
      preLoaderRoute: typeof AuthenticatedAmcRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting': {
      id: '/_authenticated/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AuthenticatedAccountingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting/': {
      id: '/_authenticated/accounting/'
      path: '/'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AuthenticatedAccountingIndexRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/users/roles': {
      id: '/_authenticated/users/roles'
      path: '/roles'
      fullPath: '/users/roles'
      preLoaderRoute: typeof AuthenticatedUsersRolesRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/accounting/periods': {
      id: '/_authenticated/accounting/periods'
      path: '/periods'
      fullPath: '/accounting/periods'
      preLoaderRoute: typeof AuthenticatedAccountingPeriodsRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/journals': {
      id: '/_authenticated/accounting/journals'
      path: '/journals'
      fullPath: '/accounting/journals'
      preLoaderRoute: typeof AuthenticatedAccountingJournalsRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/chart': {
      id: '/_authenticated/accounting/chart'
      path: '/chart'
      fullPath: '/accounting/chart'
      preLoaderRoute: typeof AuthenticatedAccountingChartRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/branch-pnl': {
      id: '/_authenticated/accounting/branch-pnl'
      path: '/branch-pnl'
      fullPath: '/accounting/branch-pnl'
      preLoaderRoute: typeof AuthenticatedAccountingBranchPnlRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/analytic': {
      id: '/_authenticated/accounting/analytic'
      path: '/analytic'
      fullPath: '/accounting/analytic'
      preLoaderRoute: typeof AuthenticatedAccountingAnalyticRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/accounts': {
      id: '/_authenticated/accounting/accounts'
      path: '/accounts'
      fullPath: '/accounting/accounts'
      preLoaderRoute: typeof AuthenticatedAccountingAccountsRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/entries/new': {
      id: '/_authenticated/accounting/entries/new'
      path: '/entries/new'
      fullPath: '/accounting/entries/new'
      preLoaderRoute: typeof AuthenticatedAccountingEntriesNewRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
  }
}

interface AuthenticatedAccountingRouteChildren {
  AuthenticatedAccountingAccountsRoute: typeof AuthenticatedAccountingAccountsRoute
  AuthenticatedAccountingAnalyticRoute: typeof AuthenticatedAccountingAnalyticRoute
  AuthenticatedAccountingBranchPnlRoute: typeof AuthenticatedAccountingBranchPnlRoute
  AuthenticatedAccountingChartRoute: typeof AuthenticatedAccountingChartRoute
  AuthenticatedAccountingJournalsRoute: typeof AuthenticatedAccountingJournalsRoute
  AuthenticatedAccountingPeriodsRoute: typeof AuthenticatedAccountingPeriodsRoute
  AuthenticatedAccountingIndexRoute: typeof AuthenticatedAccountingIndexRoute
  AuthenticatedAccountingEntriesNewRoute: typeof AuthenticatedAccountingEntriesNewRoute
}

const AuthenticatedAccountingRouteChildren: AuthenticatedAccountingRouteChildren =
  {
    AuthenticatedAccountingAccountsRoute: AuthenticatedAccountingAccountsRoute,
    AuthenticatedAccountingAnalyticRoute: AuthenticatedAccountingAnalyticRoute,
    AuthenticatedAccountingBranchPnlRoute:
      AuthenticatedAccountingBranchPnlRoute,
    AuthenticatedAccountingChartRoute: AuthenticatedAccountingChartRoute,
    AuthenticatedAccountingJournalsRoute: AuthenticatedAccountingJournalsRoute,
    AuthenticatedAccountingPeriodsRoute: AuthenticatedAccountingPeriodsRoute,
    AuthenticatedAccountingIndexRoute: AuthenticatedAccountingIndexRoute,
    AuthenticatedAccountingEntriesNewRoute:
      AuthenticatedAccountingEntriesNewRoute,
  }

const AuthenticatedAccountingRouteWithChildren =
  AuthenticatedAccountingRoute._addFileChildren(
    AuthenticatedAccountingRouteChildren,
  )

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersRolesRoute: typeof AuthenticatedUsersRolesRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersRolesRoute: AuthenticatedUsersRolesRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountingRoute: typeof AuthenticatedAccountingRouteWithChildren
  AuthenticatedAmcRoute: typeof AuthenticatedAmcRoute
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedHrRoute: typeof AuthenticatedHrRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedManufacturingRoute: typeof AuthenticatedManufacturingRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedPurchaseRoute: typeof AuthenticatedPurchaseRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedServiceRoute: typeof AuthenticatedServiceRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountingRoute: AuthenticatedAccountingRouteWithChildren,
  AuthenticatedAmcRoute: AuthenticatedAmcRoute,
  AuthenticatedBranchesRoute: AuthenticatedBranchesRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedHrRoute: AuthenticatedHrRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedManufacturingRoute: AuthenticatedManufacturingRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedPurchaseRoute: AuthenticatedPurchaseRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedServiceRoute: AuthenticatedServiceRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
