// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcwgcmgxccipdzetecua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjd2djbWd4Y2NpcGR6ZXRlY3VhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI1NzkzOTksImV4cCI6MjA5ODE1NTM5OX0.lBPuz3Yn0xqW9Nf1WKcL3fah2AIVSJJVsMw3vTPeNLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});